version: "3"

x-var: &ENV
  "development"
x-var: &DB_USER
  "gosample2021"
x-var: &DB_PASSWORD
  "password"
x-var: &DB_HOST
  "database"
x-var: &DB_NAME
  "gosample2021_development"
x-var: &DB_PORT
  3306

services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile-dev
    tty: true
    ports:
      - 8080:8080
    volumes:
      - .:/gosample2021
    environment:
      ENV: *ENV
      DB_USER: *DB_USER
      DB_PASSWORD: *DB_PASSWORD
      DB_HOST: *DB_HOST
      DB_PORT: *DB_PORT
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "5m"

  database:
    platform: linux/x86_64
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    volumes:
      - ./db-data:/var/lib/mysql
      - ./docker/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf"
    environment:
      MYSQL_ROOT_PASSWORD: root
      BIND-ADDRESS: 0.0.0.0
