// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// OfficesColumns holds the columns for the "offices" table.
	OfficesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true, Size: 25},
	}
	// OfficesTable holds the schema information for the "offices" table.
	OfficesTable = &schema.Table{
		Name:       "offices",
		Columns:    OfficesColumns,
		PrimaryKey: []*schema.Column{OfficesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		OfficesTable,
	}
)

func init() {
}
