// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/ktakenaka/gosample/ent/office"
	"github.com/ktakenaka/gosample/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	officeFields := schema.Office{}.Fields()
	_ = officeFields
	// officeDescName is the schema descriptor for name field.
	officeDescName := officeFields[0].Descriptor()
	// office.NameValidator is a validator for the "name" field. It is called by the builders before save.
	office.NameValidator = func() func(string) error {
		validators := officeDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
}
